// modules/ai-director/core/director-router.js

import { FlagFactory, PROCESS_TYPES } from "./flag-factory.js";
import {
  OllamaClient
}
from "../scripts/api/ollama-client.js";

/**
 * MASTER COMMAND ROUTER: The single orchestration hub for the AI Director module.
 * This file contains no direct Foundry hooks, DOM event handlers, or raw business logic. 
 * It receives targeted commands from hooks/UI inputs, manages sequential execution 
 * pipelines, and delegates work cleanly to stateless services.
 */
export class DirectorRouter {
    /**
     * Entry-point for routing an action request through its dedicated transaction pipeline.
     * @param {string} commandType - The explicit architectural operation to perform.
     * @param {Object} payload - Input arguments, native documents, or UI context variables.
     */
    static async dispatch(commandType, payload = {}) {
        // Enforce active GM gatekeeper status for core automation operations
        if (!game.user.isGM) return true;

        // Ensure or extract transaction correlation identifier
        const correlationId = payload.correlationId || 
                              payload.messageDoc?.flags?.["ai-director"]?.routing?.correlationId || 
                              foundry.utils.randomID();
        payload.correlationId = correlationId;

        console.log(`🛰️ AI Director Router | Command: [${commandType}] | Transaction: [${correlationId}]`);

        try {
            switch (commandType) {
                case "ROUTE_PRE_CREATE_CHAT_MESSAGE":
                    return await this._handlePreCreateChat(payload);

                case "PROCESS_DICE_RESOLUTION":
                    return await this._handleDiceResolution(payload);

                case "EXECUTE_UI_ACTION_PROMPT":
                    return await this._handleUIActionPrompt(payload);

                case "PROCESS_MULTI_NPC_CONVERSATION":
                    return await this._handleMultiNPCConversation(payload);

                default:
                    console.warn(`⚠️ AI Director Router | Unhandled command type: [${commandType}]`);
                    return true;
            }
        } catch (error) {
            console.error(`💥 AI Director Router | Critical failure routing [${commandType}] under ID [${correlationId}]:`, error);
            return true; // Pass through to avoid locking up native Foundry loops on failure
        }
    }

    /**
     * Pipeline A: Decides whether a new chat message belongs to the AI Director or skips it cleanly.
     * Replaces the old legacy MainRouter.init() preCreateChatMessage intercept loops.
     */
    static async _handlePreCreateChat({ messageDoc, initialData, options, userId }) {
        const { routing, context } = FlagFactory.getFlags(messageDoc);

        // GUARD: If process is unrecognized, missing, or untargeted, pass through instantly
        if (!routing || !routing.process || routing.process === "none") {
            return true;
        }

        // If it's already narrative output generated by the module, let it print natively
        if (routing.isAiGenerated || messageDoc.speaker?.alias === "AI Director") {
            return true; 
        }

        // Separate execution pathways based on message structural metadata
        if (messageDoc.isRoll || messageDoc.rolls?.length > 0) {
            // Re-route dice rolls immediately to the dedicated resolution service pipeline
            // Return false to intercept native mechanical output rendering in the chat log
            this.dispatch("PROCESS_DICE_RESOLUTION", { messageDoc, correlationId: routing.correlationId });
            return false; 
        }

        // If it's a standard text statement flagged for the module, handle text processing routes
        return true;
    }

    /**
     * Pipeline B: Walled-off sequence handling roll catching, lock engagement, math evaluation, and RAG compilation.
     */
    static async _handleDiceResolution({ messageDoc, correlationId }) {
        // Dynamic service imports keep file compilation contexts strictly separated
        const { acquireLock, releaseLock } = await import("../services/lock-service.js");
        const { evaluateRollOutcome } = await import("../services/roll-service.js");
        const { buildPrompt } = await import("../ai/prompt-builder-v2.js");
        const { getRelevantContext } = await import("../ai/rag-engine.js");

        // Locate originating target card to check structural memory integrity blocks
        const challengeCard = game.messages.contents
            .reverse()
            .find(m => m.flags?.["ai-director"]?.routing?.correlationId === correlationId || m.flags?.["ai-director"]?.isChallengeCard === true);

        // Acquire Concurrency Lock to block multi-client race conditions
        const lockAcquired = acquireLock(challengeCard, correlationId);
        if (!lockAcquired) return false;

        try {
            const flags = FlagFactory.getFlags(messageDoc);
            const targetDC = flags.context.targetValue || 15; // standard fallback threshold
            
            // Execute stateless mathematical/rules evaluation
            const outcome = evaluateRollOutcome(messageDoc, targetDC);
            
            // Compile RAG context vectors and local text-seed environments
            const ragContext = await getRelevantContext(flags.context.targetSkill || "Action Check");
            const outcomeContext = `The player rolled a total of ${outcome.total} against a Target DV/DC of ${targetDC}. Result: ${outcome.isSuccess ? "SUCCESS" : "FAILURE"} with a margin of ${outcome.margin}. Historical Context: ${ragContext}`;
            
            const promptPayload = await buildPrompt(outcomeContext, { mode: "action" });

            // Call Narrative Generation Service
            const { executeGMMode } = await import("../modes/gm-modes.js");
            const narrativeResult = await executeGMMode(promptPayload.system, promptPayload.user, { silent: true });

            // Compile output message card via native factory payloads
            const systemId = game?.system?.id || "cpr";
            const outputFlags = FlagFactory.createFlags({
                isAi: true,
                processType: PROCESS_TYPES.MECHANICAL_RESOLUTION,
                correlationId: correlationId,
                context: { status: "resolved", outcome: outcome.isSuccess ? "success" : "failure", rollTotal: outcome.total }
            });

            await ChatMessage.create({
                user: game.user.id,
                speaker: { alias: messageDoc.speaker?.alias || "AI Director" },
                flags: outputFlags,
                content: `
                    <div class="ai-director-chat-card system-${systemId} outcome-card" style="border: 1px solid var(--color-border-dark); background: var(--color-bg); color: var(--color-text-dark); border-radius: 4px; overflow: hidden; border-left: 4px solid ${outcome.isSuccess ? '#2ecc71' : '#e74c3c'};">
                        <div style="padding: 10px;">
                            <p style="margin: 0; font-style: italic;">"${narrativeResult}"</p>
                        </div>
                    </div>`
            });

        } finally {
            // Unconditional execution release ensures the system never catches in an absolute dead-lock state
            releaseLock(challengeCard, correlationId);
        }
    }

    /**
     * Pipeline C: Direct manual text overrides initiated from the user interface console input fields.
     */
    static async _handleUIActionPrompt({ overrideText, targetValue, correlationId }) {
        const { buildPrompt } = await import("../ai/prompt-builder-v2.js");
        const { TagInterceptor } = await import("../chat/hook-interceptor.js");

        const intentPrompt = `Player manually chose to bypass structural mechanical dice rolling arrays and provided an explicit choice declaration or tactical text adjustment. User declared statement: "${overrideText}". Target structural context check threshold values would have required beating: ${targetValue}. Formulate situational update prose matching this specific player direction.`;
        
        const promptPayload = await buildPrompt(intentPrompt, { mode: "action" });
        
        const content =
            await OllamaClient.chat(
                [
                    {
                        role: "system",
                        content: promptPayload.system
                    },
                    {
                        role: "user",
                        content: promptPayload.user
                    }
                ]
            );

        const polishedText =
            await TagInterceptor.processOutputTags(
                content,
                "AI Director"
            );

        const outputFlags = FlagFactory.createFlags({
            isAi: true,
            processType: PROCESS_TYPES.NPC_DIALOGUE,
            correlationId: correlationId
        });

        await ChatMessage.create({
            user: game.user.id,
            speaker: { alias: "AI Director" },
            content: polishedText,
            flags: outputFlags
        });
    }

    /**
     * Pipeline D: Multi-NPC Dialogue and cross-talk loops.
     */
    static async _handleMultiNPCConversation({ textInput, activeNPCs, correlationId }) {
        console.log(`🤖 Multi-NPC Processing Hook | Core path open for ${activeNPCs.length} targets.`);
        // Expansion slot: Isolates individual NPC context strings without polluting sequential execution threads
    }
}