// modules/ai-director/core/flag-factory.js

export const PROCESS_TYPES = {
  MECHANICAL_RESOLUTION: "MECHANICAL_RESOLUTION",
  SCENE_PRODUCTION: "SCENE_PRODUCTION", // Target handle for map and panorama asset-forge loops
  NPC_DIALOGUE: "NPC_DIALOGUE",
  RAW_CONVERSATION: "RAW_CONVERSATION"
};

/**
 * FLAG FACTORY: The data integrity boundary for the AI Director module.
 * Handshakes state directly with Foundry VTT's database layer inside ChatMessage documents.
 * Guarantees zero runtime property injection errors by enforcing strict schemas.
 */
export const FlagFactory = {
  /**
   * Generates a strict, nested flag structure for deterministic transaction routing.
   * @param {Object} params
   * @param {boolean} [params.isAi=true] - Marks if the message was generated by the AI system.
   * @param {string} [params.processType=PROCESS_TYPES.RAW_CONVERSATION] - One of PROCESS_TYPES.
   * @param {string|null} [params.correlationId=null] - Unique token linking asynchronous steps.
   * @param {Object} [params.context={}] - Local transactional variables (targetValue, targetSkill, etc.).
   * @returns {Object} A structural nested Foundry flags payload.
   */
  createFlags({ isAi = true, processType = PROCESS_TYPES.RAW_CONVERSATION, correlationId = null, context = {} } = {}) {
    return {
      "ai-director": {
        routing: {
          isAiGenerated: !!isAi,
          process: processType,
          correlationId: correlationId || foundry.utils.randomID(), // Enforce a transaction identity token
          timestamp: Date.now()
        },
        context: {
          status: context.status || "initialized",
          targetValue: context.targetValue || null,
          targetSkill: context.targetSkill || null,
          outcome: context.outcome || null,
          challengeContext: context.challengeContext || null,
          rollTotal: context.rollTotal || null,
          // SCENE PRODUCTION ASSET PARAMETERS
          sceneName: context.sceneName || null,
          playerScene: context.playerScene || null,
          dungeonTitle: context.dungeonTitle || null,
          manifest: context.manifest || null
        }
      }
    };
  },

  /**
   * Safely extracts and structures flags from a ChatMessage document with comprehensive fallbacks.
   * Bridges legacy flat flags and updated nested architectures without schema collisions.
   * @param {Object} messageDoc - The Foundry ChatMessage document instance.
   * @returns {Object} Structured data splitting routing boundaries from context data.
   */
  getFlags(messageDoc) {
    // Extract both current scoping root and structural system fallbacks
    const internalFlags = messageDoc?.flags?.["ai-director"] || {};
    const rootFlags = messageDoc?.flags || {};
    
    // Safely check legacy namespaces if the root module property was stored flat
    const legacyFlags = rootFlags["ai-director"] && !internalFlags.routing ? rootFlags["ai-director"] : {};

    return {
      routing: {
        isAiGenerated: internalFlags.routing?.isAiGenerated ?? legacyFlags.isAiGenerated ?? false,
        process: internalFlags.routing?.process ?? legacyFlags.process ?? "none", // 🛠️ Crucial fallback for MainRouter guard rails
        correlationId: internalFlags.routing?.correlationId ?? legacyFlags.correlationId ?? null,
        timestamp: internalFlags.routing?.timestamp ?? legacyFlags.timestamp ?? null
      },
      context: {
        status: internalFlags.context?.status ?? legacyFlags.status ?? null,
        targetValue: internalFlags.context?.targetValue ?? legacyFlags.targetValue ?? legacyFlags.targetDC ?? null,
        targetSkill: internalFlags.context?.targetSkill ?? legacyFlags.targetSkill ?? null,
        outcome: internalFlags.context?.outcome ?? legacyFlags.outcome ?? null,
        challengeContext: internalFlags.context?.challengeContext ?? legacyFlags.challengeContext ?? null,
        rollTotal: internalFlags.context?.rollTotal ?? legacyFlags.rollTotal ?? null,
        // RETRIEVAL MAPPING HOOKS FOR FORGE ENGINES
        sceneName:
          internalFlags.context?.sceneName ??
          legacyFlags.sceneName ??
          null,
        
        playerScene:
          internalFlags.context?.playerScene ??
          legacyFlags.playerScene ??
          null,
        
        dungeonTitle:
          internalFlags.context?.dungeonTitle ??
          legacyFlags.dungeonTitle ??
          null,
        
        manifest:
          internalFlags.context?.manifest ??
          legacyFlags.manifest ??
          null
      }
    };
  }
};