// modules/ai-director/core/main-router.js

// 1. Same-folder imports (Core orchestration modules)
import { FlagFactory, PROCESS_TYPES } from "./flag-factory.js";

// 2. Relative step-out paths (Moving up one directory level to reach sibling folders)
import { buildPrompt } from "../scripts/ai/prompt-builder.js";        // Steps out of core/ to reach ai/
import { TagInterceptor } from "../scripts/chat/tag-interceptor.js";     // Steps out of core/ to reach chat/
import { OllamaClient } from "../scripts/api/ollama-client.js";          // Steps out of core/ to reach api/
import { parseChatMessage } from "../scripts/ai/parser.js";            // Grab your chat telemetry parser
import { postToChat } from "../scripts/chat/chat-handler.js";            // Grab your chat dispatch service
import { logSocialInteraction } from "../scripts/ai/short-term-telemetry.js";

export const MainRouter = {
  init() {
    // PASS 1: Boundary Guard Rail Interceptor
    Hooks.on("preCreateChatMessage", (messageDoc, initialData, options, userId) => {
      if (!game.user.isGM) return true;

      const { routing, context } = FlagFactory.getFlags(messageDoc);

      // 🛡️ GUARD: Instant pass-through if this is part of the modern sandboxed skill sequence
      const processType = messageDoc.flags?.["ai-director"]?.process || routing?.process;
      if (processType === "SKILL_CHECK_SEQUENCE") {
        return true;
      }

      // Instant pass-through if unrecognized or untargeted
      if (!routing || !routing.process || routing.process === "none" || routing.targetEngine === "none") {
        return true;
      }

      // If it's already an explicit narrative output generated by the AI, let it print cleanly
      if (routing.isAiGenerated || messageDoc.speaker?.alias === "AI Director") {
        return true; 
      }

      // Route explicitly by typed metadata structures
      if (messageDoc.isRoll || messageDoc.rolls?.length > 0) {
        return MainRouter._routeRollMessage(messageDoc, routing);
      } else {
        return MainRouter._routeTextMessage(messageDoc, routing, context);
      }
    });

    // PASS 2: Downstream Execution Interceptor (Marries Dice Loops Deterministically)
    Hooks.on("createChatMessage", (messageDoc, options, userId) => {
      if (!game.user.isGM) return;

      const { routing } = FlagFactory.getFlags(messageDoc);

      // 🛡️ GUARD: Prevent downstream evaluation if handled by sandboxed SkillCheckOrchestrator
      const processType = messageDoc.flags?.["ai-director"]?.process || routing?.process;
      if (processType === "SKILL_CHECK_SEQUENCE") {
        return;
      }

      if (!routing || !routing.process || routing.process === "none" || routing.targetEngine === "none") {
        return;
      }

      // Intercept execution loop ONLY if stamped for explicit resolution
      if (routing.process === PROCESS_TYPES.MECHANICAL_RESOLUTION && !routing.isAiGenerated) {
        MainRouter._handleEvaluatedRoll(messageDoc, routing);
      }
    });
  },

  /**
   * Stamps an in-flight dice roll with structural identity headers.
   */
  _routeRollMessage(messageDoc, routing) {
    if (routing.process !== PROCESS_TYPES.MECHANICAL_RESOLUTION) {
      const updatedFlags = FlagFactory.createFlags({
        isAi: false,
        processType: PROCESS_TYPES.MECHANICAL_RESOLUTION,
        correlationId: routing.correlationId
      });
      messageDoc.updateSource({ "flags.ai-director": updatedFlags["ai-director"] });
    }
    return true;
  },

  /**
   * Processes textual input entries captured within an active module workflow.
   */
  _routeTextMessage(messageDoc, routing, context) {
    if (routing.process === PROCESS_TYPES.SCENE_PRODUCTION) {
      return true; 
    }

    if (routing.correlationId) {
      const sourceCard = game.messages.get(routing.correlationId);
      if (sourceCard) {
        const cleanText = (messageDoc.content || "").replace(/<[^>]*>/g, '').trim();
        const actorName = ChatMessage.getSpeakerActor(messageDoc.speaker)?.name || messageDoc.speaker?.alias || "The Player";
        
        MainRouter._handleChallengeCardOverride(sourceCard, cleanText, actorName, routing.correlationId);
        return false; // Suppress original raw chat input from flooding the sidebar log
      }
    }

    return true;
  },

  /**
   * Evaluates a completed game-system dice roll against explicit context difficulty thresholds.
   */
  async _handleEvaluatedRoll(messageDoc, routing) {
    if (!routing.correlationId) return;
    const sourceCard = game.messages.get(routing.correlationId);
    if (!sourceCard) return;

    const parentFlags = FlagFactory.getFlags(sourceCard);
    const targetValue = parentFlags.context.targetValue || 15;

    const rollTotal = messageDoc.rolls?.[0]?.total || messageDoc.roll?.total || 0;
    const isSuccess = rollTotal >= targetValue;

    const originalActionText = messageDoc.content || "";
    const feedbackHeader = `
      <div style="margin-bottom: 8px; font-family: var(--font-primary);">
        <strong style="text-transform: uppercase;">System Determination:</strong> 
        <span style="color: ${isSuccess ? '#2b7a3e' : '#ba2d2d'}; font-weight: bold;">[${isSuccess ? 'SUCCESS' : 'FAILURE'}]</span><br>
        <span style="font-size: 0.9em; opacity: 0.85;">The check total (${rollTotal}) ${isSuccess ? 'beats or meets' : 'falls short of'} the challenge threshold of ${targetValue}.</span>
      </div>
      ${originalActionText}
      <hr style="border: 0; border-top: 1px dashed rgba(0,0,0,0.2); margin: 8px 0;">
    `;

    // Package results back inside our modular contract
    const executionFlags = FlagFactory.createFlags({
      isAi: false,
      processType: PROCESS_TYPES.MECHANICAL_RESOLUTION,
      correlationId: routing.correlationId,
      context: {
        rollTotal: rollTotal,
        targetValue: targetValue,
        outcome: isSuccess ? "success" : "failure"
      }
    });

    await messageDoc.update({
      content: feedbackHeader + messageDoc.content,
      "flags.ai-director": executionFlags["ai-director"]
    });

    const rawIntentText = parentFlags.context.challengeContext || "Standard Action Check";
    const narrativeInput = `The player attempted an action matching intent frame: "${rawIntentText}". Roll total was ${rollTotal} against a required target threshold of ${targetValue}. The mechanical outcome is a definitive ${isSuccess ? 'SUCCESS' : 'FAILURE'}. Adjust next narrative development segment accordingly.`;

    try {
      const modeMapping = game.settings.get("ai-director", "systemType") === "sw5e" ? "action" : "npc";
      const promptPayload = await buildPrompt(narrativeInput, { mode: modeMapping });
      
      const messages = [
        { role: "system", content: promptPayload.system },
        { role: "user", content: promptPayload.user }
      ];
      
      const rawAiText = await OllamaClient.chat(messages, { temperature: 0.5 });
      const polishedText = await TagInterceptor.processOutputTags(rawAiText, null);
      
      const outputFlags = FlagFactory.createFlags({
        isAi: true,
        processType: PROCESS_TYPES.MECHANICAL_RESOLUTION,
        correlationId: routing.correlationId
      });

      await ChatMessage.create({
        user: game.user.id,
        speaker: { alias: "AI Director" },
        content: polishedText,
        flags: outputFlags
      });
    } catch (err) {
      console.error("AI Director | Execution engine loop transaction failure:", err);
    }
  },

  /**
   * Handles explicit text input changes targeted at a specific active challenge step.
   */
  async _handleChallengeCardOverride(sourceCard, overrideText, actorName, correlationId) {
    const parentFlags = FlagFactory.getFlags(sourceCard);
    const targetValue = parentFlags.context.targetValue || 15;

    const intentPrompt = `The user bypassed mechanical dice rolling arrays and provided an explicit choice declaration or tactical text adjustment. User declared statement: "${overrideText}". Target structural context check threshold values would have required beating: ${targetValue}. Formulate situational update prose matching this specific player direction.`;

    try {
      const promptPayload = await buildPrompt(intentPrompt, { mode: "action" });
      
      const messages = [
        { role: "system", content: promptPayload.system },
        { role: "user", content: promptPayload.user }
      ];

      const rawAiText = await OllamaClient.chat(messages, { temperature: 0.5 });
      const polishedText = await TagInterceptor.processOutputTags(rawAiText, null);

      const outputFlags = FlagFactory.createFlags({
        isAi: true,
        processType: PROCESS_TYPES.NPC_DIALOGUE,
        correlationId: correlationId
      });

      await ChatMessage.create({
        user: game.user.id,
        speaker: { alias: "AI Director" },
        content: polishedText,
        flags: outputFlags
      });
    } catch (err) {
      console.error("AI Director | Input override pipeline execution error:", err);
    }
  }
};